<?php if(!defined('ABSPATH')) {
	die('Direct access forbidden.');
}
/**
 * Dynamic CSS, generated by customizer options
 */

if(class_exists('CSF')) {

	$body_bg_url = '';
	$general_box_bg_image_url = '';
	$page_box_bg_image_url = '';
	$typography = instive_option('typography');
	$body_bg = instive_option('style_body_bg', '#fff');
	$style_body_color = instive_option('style_body_color', '#5a5a5a');
	$style_primary = instive_option('style_primary', '#003478');
	$title_color = instive_option('title_color', '#003478');
	$style_primary_dark = instive_option('style_primary_dark', '#00449e');
	$secondary_color = instive_option('secondary_color', '#00449e');
	$general_body_box_layout = instive_option("general_body_box_layout");
	$page_body_box_layout = instive_meta_option(get_the_ID(), "page_body_box_layout");

	$page_override_header_item = instive_meta_option(get_the_ID(), 'page_header_override');
	$page_header_layout_style_item = instive_meta_option(get_the_ID(), 'page_header_layout_style');
	// banner overlay color
	$sub_page_banner_overlay_style = instive_option('sub_page_banner_overlay_style', 'rgba(0, 0, 0, 0.4)');

	if(isset($general_body_box_layout["yes"])) {
		$box_bg_image = $general_body_box_layout["yes"];
		if(isset($box_bg_image["general_body_box_bg_image"])) {

			if(is_array($box_bg_image["general_body_box_bg_image"])) {

				$general_box_bg_image_url = $box_bg_image["general_body_box_bg_image"]["url"];

			}

		}
	}

	$global_body_font = instive_option('body_font');

	Instive_Unyson_Google_Fonts::add_typography_v2($global_body_font);
	$body_font = instive_advanced_font_styles($global_body_font);

	$heading_font_one = instive_option('heading_font_one');
	Instive_Unyson_Google_Fonts::add_typography_v2($heading_font_one);
	$heading_font_one = instive_advanced_font_styles($heading_font_one);

	$heading_font_two_style = instive_option('heading_font_two_style');
	Instive_Unyson_Google_Fonts::add_typography_v2($heading_font_two_style);
	$heading_font_two_style = instive_advanced_font_styles($heading_font_two_style);

	$heading_font_two = instive_option('heading_font_two');
	Instive_Unyson_Google_Fonts::add_typography_v2($heading_font_two);
	$heading_font_two = instive_advanced_font_styles($heading_font_two);

	$heading_font_three = instive_option('heading_font_three');
	Instive_Unyson_Google_Fonts::add_typography_v2($heading_font_three);
	$heading_font_three = instive_advanced_font_styles($heading_font_three);

	// init custom css
	$custom_css = instive_option('custom_css');
	$output = $custom_css;

	// global style
	$output .= "
        body{ $body_font }

        body,
        .sidebar ul li a,
        body.blog, body.single-post, body.page, body.search.search-results{
            color: $style_body_color;
        }

        h1{
            $heading_font_one
        }
        h2,
        .post .entry-header .entry-title,
        article.page .entry-header .entry-title {
            $heading_font_two_style
        }
        h3{ 
            $heading_font_two 
        }

        h4{ 
            $heading_font_three
        }

        .banner-bg::after,
        .banner-area::after{
            background-color: $sub_page_banner_overlay_style;
        }

       

        a, .post-meta span i, .entry-header .entry-title a:hover, .sidebar ul li a:hover{
            color: $style_primary;
            transition: all ease 500ms;
        }
        .header ul.navbar-nav > li > a:hover,
         .header ul.navbar-nav > li > a.active,
         .header ul.navbar-nav > li > a:focus,
         .post .entry-header .post-meta span i, 
         article.page .entry-header .post-meta span i,
         .post .entry-header .post-meta span a:hover, article.page .entry-header .post-meta span a:hover,
         .post .entry-header .entry-title a:hover,
          article.page .entry-header .entry-title a:hover,
         .sidebar .widget .widget-title a:hover,
         h1, h2, h3, h4, h5, h6,
         .sidebar .widget .entry-title a:hover,
         .sidebar .ts-social-list li a,
         .wp-block-quote:before,
         a.btn-link,
         .testimoial-wrap .testimonial-content .testimonial-meta .ts-title,
         .testimoial-wrap .testimonial-content p:before,
         .post-navigation span:hover, .post-navigation h3:hover,
         .related-post-area .ts-title a:hover,
         a.btn-link:hover,
         .woocommerce ul.products li.product .woocommerce-loop-product__title:hover,
        .banner-area .breadcrumb i,
        .post-details .entry-header .post-meta span i,
        .banner-area .banner-title span,
        .woocommerce-message::before,
        .woocommerce-info::before {
            color: $style_primary;
        }

         .entry-header .entry-title a,
      
         .post .entry-header .entry-title a, article.page .entry-header .entry-title a,
         .sidebar .widget .widget-title a,
         h1, h2, h3, h4, h5, h6,
         .sidebar .widget .entry-title a,
         .related-post-area .ts-title a,
         .sidebar ul li a.url, .sidebar ul li a.rsswidget{
            color: $title_color;
            
        }
        
        .sidebar .widget.widget_search .instive-serach .input-group-btn,
        .btn,
        .testimoial-wrap .testimonial-content h3.ts-title,
        .ts-service-slider .ts-feature-box .btn.quote-btn,
        .sidebar .ts-social-list li a:hover,
        #preloader,
        .woocommerce ul.products li.product .button,.woocommerce ul.products li.product .added_to_cart,
        .woocommerce nav.woocommerce-pagination ul li a:focus, .woocommerce nav.woocommerce-pagination ul li a:hover, .woocommerce nav.woocommerce-pagination ul li span.current,
        .woocommerce #respond input#submit.alt, .woocommerce a.button.alt, .woocommerce button.button.alt, .woocommerce input.button.alt,.sponsor-web-link a:hover i, .woocommerce .widget_price_filter .ui-slider .ui-slider-range,
        .woocommerce span.onsale,
        .navbar-light .navbar-toggler,
        .ts-contact-form .form-group .btn-submit:hover,
        .woocommerce table.cart td.actions button.button,
        .woocommerce a.button, .woocommerce button.button.alt,
        .faq .elementor-accordion .elementor-accordion-item .elementor-tab-title.elementor-active .elementor-accordion-icon,
        .woocommerce ul.products li.product .added_to_cart:hover, .woocommerce #respond input#submit.alt:hover, .woocommerce a.button.alt:hover, .woocommerce button.button.alt:hover, .woocommerce input.button.alt:hover,.woocommerce .widget_price_filter .ui-slider .ui-slider-handle,
        .project-wrapper .project-carousel .project-content .instive-btn {
            background-color: $style_primary; 
        }
        .btn:hover
        {
            background-color:  $secondary_color;
            border-color:  $secondary_color;
        }
        .dot-style2 .owl-dots .owl-dot.active span,
        .testimoial-wrap .testimonial-content .testimonial-author-img,
        .owl-carousel .owl-dots .owl-dot.active span,
        .woocommerce div.product .woocommerce-tabs ul.tabs li.active,
        .woocommerce-message,
        .woocommerce-info{
            border-color: $style_primary; 
        }
        ";

	// footer style


	$footer_copyright_color = instive_option('footer_copyright_color', '#ffffff');
	$footer_bg_color = instive_option('footer_bg_color', '#003478');


	$output .= "
      body{
         background-color: $body_bg;
      }
     
  
      .copy-right {
         background: $footer_bg_color;
      }
      .copy-right .copyright-text{
         color: $footer_copyright_color;
      }
      ";

	wp_add_inline_style('instive-master', $output);


}